apiVersion: v1
kind: Secret
metadata:
  name: shapeblock-credentials
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  api-key: {{ required "A valid API key is required" .Values.credentials.apiKey }}
  license-key: {{ required "A valid license key is required" .Values.credentials.licenseKey }}
  license-email: {{ required "A valid license email is required" .Values.credentials.licenseEmail }}
