apiVersion: apps.shapeblock.io/v1alpha1
kind: AppBuild
metadata:
  name: fl-build-1
  namespace: py-dev2
spec:
  appName: "fl"
  gitRef: "main"
  imageTag: "v1"

  helmValues:
    releasePrefix: "fl"

    deployments:
      python:
        containers:
          - name: python
            envConfigmaps:
              - envs
            livenessProbe:
              tcpSocket:
                port: 8080
            ports:
              - containerPort: 8080
                name: app
            resources:
              limits:
                cpu: "1"
                memory: 2Gi
              requests:
                cpu: 5m
                memory: 128M
        podLabels:
          release: fl
        replicas: 1

    envs:
      PORT: "8080"
      FOO: "bar1"

    generic:
      extraImagePullSecrets:
        - name: registry-creds
      labels:
        release: fl
        timestamp: "1737611778"
      usePredefinedAffinity: false

    ingresses:
      "py-dev2-fl.without-op.shapeblockapp.com":
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 50m
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        certManager:
          originalIssuerName: letsencrypt-prod
          issuerType: cluster-issuer
        hosts:
          - paths:
              - serviceName: python
                servicePort: 8080
        ingressClassName: nginx
        name: py-dev2-fl

    services:
      python:
        extraSelectorLabels:
          release: fl
        ports:
          - port: 8080
        type: NodePort

