apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op2
  name: sb-app-viewer-role
rules:
- apiGroups:
  - apps.shapeblock.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.shapeblock.io
  resources:
  - apps/status
  verbs:
  - get
