# permissions for end users to edit appbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: op2
    app.kubernetes.io/managed-by: kustomize
  name: appbuild-editor-role
rules:
- apiGroups:
  - apps.shapeblock.io
  resources:
  - appbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.shapeblock.io
  resources:
  - appbuilds/status
  verbs:
  - get
