# permissions for end users to view appbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: op2
    app.kubernetes.io/managed-by: kustomize
  name: appbuild-viewer-role
rules:
- apiGroups:
  - apps.shapeblock.io
  resources:
  - appbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.shapeblock.io
  resources:
  - appbuilds/status
  verbs:
  - get
