apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.apps.shapeblock.io
spec:
  group: apps.shapeblock.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              displayName:
                type: string
              description:
                type: string
                maxLength: 256
              owner:
                type: string
              resourceQuota:
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  storage:
                    type: string
                type: object
            required:
            - displayName
            type: object
          status:
            properties:
              phase:
                type: string
              message:
                type: string
              namespaceCreated:
                type: boolean
              quotaConfigured:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: Display Name
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
