apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appbuilds.apps.shapeblock.io
spec:
  group: apps.shapeblock.io
  names:
    kind: AppBuild
    listKind: AppBuildList
    plural: appbuilds
    singular: appbuild
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              appName:
                type: string
              imageTag:
                type: string
              buildType:
                type: string
                enum: ["dockerfile", "buildpack", "prebuilt"]
              git:
                properties:
                  url:
                    type: string
                  ref:
                    type: string
                  sshKeySecret:
                    type: string
                required:
                - url
                - ref
                type: object
              registryURL:
                type: string
              previousImage:
                type: string
              builderImage:
                type: string
              buildVars:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  required:
                  - key
                  - value
                  type: object
                type: array
              isPrivate:
                type: boolean
              helmValues:
                # Allow any valid YAML/JSON structure
                x-kubernetes-preserve-unknown-fields: true
                type: object
            required:
            - appName
            - imageTag
            - buildType
            - registryURL
            type: object
          status:
            properties:
              phase:
                type: string
              message:
                type: string
              podName:
                type: string
              podNamespace:
                type: string
              startTime:
                format: date-time
                type: string
              completionTime:
                format: date-time
                type: string
              logs:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
