apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.apps.shapeblock.io
spec:
  group: apps.shapeblock.io
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              appName:
                type: string
              chart:
                type: object
                required: ["name"]
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  repo:
                    type: string
                  repoURL:
                    type: string
              image:
                properties:
                  repository:
                    type: string
                  tag:
                    type: string
                  pullPolicy:
                    type: string
                required:
                - repository
                - tag
                type: object
              helmValues:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
            - appName
            - chart
            type: object
          status:
            properties:
              phase:
                type: string
              message:
                type: string
              helmRelease:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .spec.appName
      name: App
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.url
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
